version: "3"
services:
  step_to_obj_converter:
    build: step_to_obj_conversion/
    image: drescherflo/ma_step_to_obj_converter
    volumes:
      - "${CUSTOM_DATASET_DIR}/cad_models/STEP/:/step_models/:rw"
      - "${CUSTOM_DATASET_DIR}/cad_models/OBJ/:/obj_models/:rw"
    command: [ "--input_dir", "/step_models",
               "--output_dir", "/obj_models" ]
    profiles: [ "manual" ]  # Disable autostart with compose up
  obj_to_usd_converter:
    image: nvcr.io/nvidia/isaac-sim:2023.1.1
    environment:
      - ACCEPT_EULA=Y
    volumes:
      - "${CUSTOM_DATASET_DIR}/cad_models/:/cad_models/:rw"
    entrypoint: [ "./python.sh", "standalone_examples/api/omni.kit.asset_converter/asset_usd_converter.py" ]
    command: [ "--folders", "/cad_models/OBJ" ]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    profiles: [ "manual" ]  # Disable autostart with compose up
  config_generator_for_6_dof_dataset_generation:
    build: custom_dataset/dataset_generation/config_generation/
    image: drescherflo/ma_config_generator_for_dataset_generation
    volumes:
      - "${CUSTOM_DATASET_DIR}/cad_models/OBJ_converted/:/usd_models/:ro"
      - "${CUSTOM_DATASET_DIR}/dataset_generator_configs/:/dataset_generator_configs/:rw"
    command: [ "--usd_dir", "/usd_models",
               "--out_path", "/dataset_generator_configs/6_dof_generator_config.json",
               "--num_frames_per_object", "1000" ]
    profiles: [ "manual" ]  # Disable autostart with compose up
  6_dof_dataset_generator:
    image: nvcr.io/nvidia/isaac-sim:2023.1.1
    environment:
      - ACCEPT_EULA=Y
    volumes:
      - "./custom_dataset/dataset_generation/data_generation/:/data_generation/:ro"
      - "${CUSTOM_DATASET_DIR}/cad_models/OBJ_converted/:/usd_models/:ro"
      - "${CUSTOM_DATASET_DIR}/dataset_generator_configs/:/dataset_generator_configs/:ro"
      - "${CUSTOM_DATASET_DIR}/replicator_dataset/:/replicator_dataset/:rw"
    entrypoint: [ "./python.sh", "/data_generation/6_dof_dataset_generator.py" ]
    command: [ "--headless",
               "--output_dir", "/replicator_dataset/6_dof",
               "--usd_dir", "/usd_models",
               "--config_file", "/dataset_generator_configs/6_dof_generator_config.json",
               "--writer", "ResumableBasicWriter", "rgb=True", "camera_params=True",
               "--writer", "WorldPoseWriter" ]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    profiles: [ "manual" ]  # Disable autostart with compose up
  config_generator_for_conveyor_belt_dataset_generation:
    build: custom_dataset/dataset_generation/config_generation/
    image: drescherflo/ma_config_generator_for_dataset_generation
    volumes:
      - "${CUSTOM_DATASET_DIR}/cad_models/OBJ_converted/:/usd_models/:ro"
      - "${CUSTOM_DATASET_DIR}/dataset_generator_configs/:/dataset_generator_configs/:rw"
    entrypoint: ["python", "conveyor_config_generator.py"]
    command: [ "--usd_dir", "/usd_models",
               "--out_path", "/dataset_generator_configs/conveyor_generator_config.json",
               "--object_init_min_x", "-6.0",
               "--object_init_max_x", "2.0",
               "--conveyor_belt_speed", "0.2",
               "--num_objects_per_scene", "200",
               "--num_frames_per_scene", "100",
               "--num_scenes_per_object", "10"]
    profiles: [ "manual" ]  # Disable autostart with compose up
  conveyor_dataset_generator:
    image: nvcr.io/nvidia/isaac-sim:2023.1.1
    environment:
      - ACCEPT_EULA=Y
    volumes:
      - "./custom_dataset/dataset_generation/data_generation/:/data_generation/:ro"
      - "${CUSTOM_DATASET_DIR}/cad_models/OBJ_converted/:/usd_models/:ro"
      - "${CUSTOM_DATASET_DIR}/dataset_generator_configs/:/dataset_generator_configs/:ro"
      - "${CUSTOM_DATASET_DIR}/replicator_dataset/:/replicator_dataset/:rw"
    entrypoint: [ "./python.sh", "/data_generation/conveyor_belt_dataset_generator.py" ]
    command: [ "--headless",
               "--output_dir", "/replicator_dataset/conveyor_belt",
               "--usd_dir", "/usd_models",
               "--config_file", "/dataset_generator_configs/conveyor_generator_config.json",
               "--writer", "ResumableBasicWriter", "rgb=True", "camera_params=True",
               "--writer", "WorldPoseWriter" ]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    profiles: [ "manual" ]  # Disable autostart with compose up
  dataset_converter:
    build: custom_dataset/dataset_conversion/
    image: drescherflo/ma_dataset_converter
    volumes:
      - "./custom_dataset/dataset_conversion/converter_plugins/:/dataset_converter/converter_plugins/:ro"  # Override plugin dir, so new plugins can be added without rebuilding image
      - "${CUSTOM_DATASET_DIR}/cad_models/OBJ/:/obj_models/:ro"
      - "${CUSTOM_DATASET_DIR}/replicator_dataset/:/replicator_dataset/:ro"
      - "${CUSTOM_DATASET_DIR}/converted/:/converted_datasets/:rw"
    command: [ "--obj_dir", "/obj_models",
               "--replicator_data_dir", "/replicator_dataset/6_dof",
               "--replicator_data_dir", "/replicator_dataset/conveyor_belt",
               "--output_dir", "/converted_datasets"
               "--converter", "ReplicatorToRoca"]
    profiles: [ "manual" ]  # Disable autostart with compose up

